---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-alertmanager
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: "/pv/prometheus-alertmanager/"
...
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-server
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 8Gi
  hostPath:
    path: "/pv/prometheus-server/"
...
