---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-alertmanager
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: "/data"
...
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-pushgateway
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: "/data"
...
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-server
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 8Gi
  hostPath:
    path: "/data"
...
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: "/data/grafana"
...
